name: Build Flask TTS App

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install black flake8

      - name: Format code with black
        run: black --line-length 79 app.py

      - name: Lint with flake8
        run: flake8 app.py