name: Build Flask TTS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Workaround for lsb_release version bug
        run: |
          sudo sed -i 's/6.11.0-1014-azure/20.04/' /etc/lsb-release || true
          sudo sed -i 's/6.11.0-1014-azure/20.04/' /etc/os-release || true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app.py

      - name: Archive app
        run: |
          zip -r tts_project.zip app.py templates/ requirements.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tts_project_build
          path: tts_project.zip