name: Build Flask TTS App

on:
  push:
    branches: [main, 3-fix-the-workflow-error]
  pull_request:
    branches: [main, 3-fix-the-workflow-error]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app.py

      - name: Archive app
        run: |
          zip -r tts_project.zip app.py templates/ requirements.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tts_project_build
          path: tts_project.zip