name: Build Flask TTS App

on:
  push:
    branches: [main, 3-fix-the-workflow-error]
  pull_request:
    branches: [main, 3-fix-the-workflow-error]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: python:3.11-bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            gcc \
            libffi-dev \
            libsndfile1 \
            libasound2-dev \
            libpython3-dev \
            git \
            curl

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app.py || true

      - name: Archive app
        run: |
          zip -r tts_project.zip app.py templates/ requirements.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tts_project_build
          path: tts_project.zip
